spring.application.name=jobtracker
logging.level.root=INFO
logging.level.com.jobtracker=DEBUG
spring.mongodb.uri=mongodb://localhost:27017/jobtracker
spring.mongodb.database=jobtracker
spring.devtools.restart.enabled=false
telegram.bot.token=8879911666:AAEZ287FqSPrtYODDDh24LOcgDx5z25pBGA
telegram.chat.id=8590153144
candidate.skills=Java,Spring Boot,Spring MVC,Microservices,REST API,Kafka,JPA,Hibernate,Spring Framework,JUnit,Git,GitHub,Maven,Gradle,NoSQL,SQL,Agile,RESTful,API,Microservice,AWS,Cloud
candidate.experience=3
candidate.roles=Software Engineer,Backend Engineer,Java Developer,Software Development Engineer