spring.application.name=jobtracker
logging.level.root=INFO
logging.level.com.jobtracker=DEBUG
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
spring.mongodb.uri=${MONGO_URI}
spring.devtools.restart.enabled=false
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.chat.id=${TELEGRAM_CHAT_ID}
logging.level.org.springframework.data.mongodb=ERROR
candidate.skills=Java,Spring Boot,Spring MVC,Microservices,REST API,Kafka,JPA,Hibernate,Spring Framework,JUnit,Git,GitHub,Maven,Gradle,NoSQL,SQL,Agile,RESTful,API,Microservice,AWS,Cloud
candidate.experience=3
candidate.roles=Software Engineer,Backend Engineer,Java Developer,Software Development Engineer,Java Full Stack Developer,Full Stack Developer,Software Developer,Software Development