spring.application.name=jobtracker
logging.level.root=INFO
logging.level.com.jobtracker=DEBUG
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
spring.mongodb.uri=${MONGO_URI}
spring.devtools.restart.enabled=false
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.chat.id=${TELEGRAM_CHAT_ID}
logging.level.org.springframework.data.mongodb=ERROR